### ISSUE TITLE
nagios configuration

### ISSUE THREAD

**Issue by fmontaldo** [ITRS-Group/system-addons-plugins-op5-check_vmware_api#20]
Hi,

I installed the plugin but one library is missing.

[root@ardc01nagios check_vmware_api]# ./check_vmware_api.pl -H IP-f check_vmware_api.auth -l cpu -s usage -w 80 -c 90
Can't locate Net/SSL.pm in @INC (@INC contains: /root/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/x86_64-linux /root/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3 /root/perl5/perlbrew/perls/perl-5.16.3/lib/5.16.3/x86_64-linux /root/perl5/perlbrew/perls/perl-5.16.3/lib/5.16.3 .) at ./check_vmware_api.pl line 44.
BEGIN failed--compilation aborted at ./check_vmware_api.pl line 44.
You have new mail in /var/spool/mail/root

Can you please help to resolve this?.

**Comment by fmikker** [comment]
Hi,
what platform/OS are your running the check on?

**Comment by fmotnaldo** [comment]
Hi,

I am running the plugin under rhel 6.9.

**Comment by fmikker** [comment]
@fmotnaldo Have you made sure that the following dependencies are installed as the README suggests?
$ sudo yum install openssl-devel perl-Archive-Zip perl-Class-MethodMaker uuid-perl perl-SOAP-Lite perl-XML-SAX perl-XML-NamespaceSupport perl-XML-LibXML perl-MIME-Lite perl-MIME-Types perl-MailTools perl-TimeDate uuid libuuid perl-Data-Dump perl-UUID cpan libxml2-devel perl-libwww-perl perl-Test-MockObject perl-Test-Simple perl-Monitoring-Plugin perl-Class-Accessor perl-Config-Tiny

**Comment by fmotnaldo** [comment]
Yes I got all of the packages. I installed this sdk version.

VMware-vSphere-Perl-SDK-5.5.0-2043780.x86_64.tar.gz

Teh version of ESXi is 6.5.0 Update 1 (Build 6765664)

**Comment by fmikker** [comment]
> Can't locate Net/SSL.pm in @inc (@inc contains: /root/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/x86_64-linux /root/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3 /root/perl5/perlbrew/perls/perl-5.16.3/lib/5.16.3/x86_64-linux /root/perl5/perlbrew/perls/perl-5.16.3/lib/5.16.3 .) 

This path looks really wierd, it should look like this on a EL6 system:
# find / -name SSL.pm
/usr/lib64/perl5/vendor_perl/Net/SSL.pm

It looks like you have been using perlbrew somehow, this is untested and not recommended.

Run the command above and come back with the results.

**Comment by fmotnaldo** [comment]
This is the output for the find command

find / -name SSL.pm
/usr/lib64/perl5/vendor_perl/Net/SSL.pm
/usr/share/perl5/vendor_perl/IO/Socket/SSL.pm
/tmp/vmware-vsphere-cli-distrib/lib/Crypt-SSLeay-0.55-0.9.8/lib/Net/SSL.pm
/tmp/vmware-vsphere-cli-distrib/lib/Crypt-SSLeay-0.55-0.9.7/lib/Net/SSL.pm
/tmp/vmware-vsphere-cli-distrib/lib/5.10/Crypt-SSLeay-0.55-0.9.8/lib/Net/SSL.pm
/tmp/vmware-vsphere-cli-distrib/lib/5.10/Crypt-SSLeay-0.55-0.9.7/lib/Net/SSL.pm

**Comment by fmotnaldo** [comment]
I just fix the issue with a cpan upgrade but now I need to know the way to configure the check to unr under nagios. When I try to test it it shoes this:

[root@ardc01nagios check_vmware_api]# ./generate_tests.pl
CHECK_VMWARE_API.PL UNKNOWN - plugin timed out (timeout 30s)
CHECK_VMWARE_API.PL UNKNOWN - plugin timed out (timeout 30s)
CHECK_VMWARE_API.PL UNKNOWN - plugin timed out (timeout 30s)
CHECK_VMWARE_API.PL UNKNOWN - plugin timed out (timeout 30s)

**Comment by fmikker** [comment]
Hi,
this might be related: https://jira.op5.com/browse/MON-10348
As well as #15

**Comment by fmikker** [comment]
#15

**Comment by jacobbaungard** [comment]
This plugin is "deprecated" from our side, and so most likely won't see any updates. We are therefore closing all open issues. Sorry about that.

The following project, which was forked from this one, might be of interest to you: https://github.com/BaldMansMojo/check_vmware_esx/
