### ISSUE TITLE
Getting error while command exeution

### ISSUE THREAD

**Issue by cxadmin** [ITRS-Group/system-addons-plugins-op5-check_vmware_api#21]
OS: Centos 7.2
I have issue with command execution
/usr/bin/perl: symbol lookup error: /usr/lib64/perl5/auto/Crypt/SSLeay/SSLeay.so: undefined symbol: Perl_Gthr_key_ptr

**Comment by jacobbaungard** [comment]
This plugin is "deprecated" from our side, and so most likely won't see any updates. We are therefore closing all open issues. Sorry about that.

The following project, which was forked from this one, might be of interest to you: https://github.com/BaldMansMojo/check_vmware_esx/
