### ISSUE TITLE
Feature request: VM Disk Usage

### ISSUE THREAD

**Issue by noctrex** [ITRS-Group/system-addons-plugins-op5-check_vmware_api#24]
Is it possible to extract the Disk Usage from at the VM level?
I've seen this page:
https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.vm.GuestInfo.DiskInfo.html
and wonder if it can me implemented

**Comment by jacobbaungard** [comment]
This plugin is "deprecated" from our side, and so most likely won't see any updates. We are therefore closing all open issues. Sorry about that.

The following project, which was forked from this one, might be of interest to you: https://github.com/BaldMansMojo/check_vmware_esx/
