### ISSUE TITLE
unknown runtim health after upgrade 6.7

### ISSUE THREAD

**Issue by prohand** [ITRS-Group/system-addons-plugins-op5-check_vmware_api#25]
Hello

After migration in 6.7 I encounter this problem:

`1) UNKNOWN[other] Status of System Management Software 1 Low Security Jmp: Cannot report on the current health state of the element
2) UNKNOWN[other] Status of System Management Software 1 Phy Presence Jmp: Cannot report on the current health state of the element
3) UNKNOWN[Storage] Status of Intel Corporation Xeon E7 v4/Xeon E5 v4/Xeon E3 v4/Xeon D DMI2 #0: Cannot report on the current status of the physical element
4) UNKNOWN[Storage] Status of Intel Corporation Xeon E7 v4/Xeon E5 v4/Xeon E3 v4/Xeon D PCI Express Root Port 1 #1: Cannot report on the current status of the physical element
5) UNKNOWN[Storage] Status of Intel Corporation Xeon E7 v4/Xeon E5 v4/Xeon E3 v4/Xeon D PCI Express Root Port 3 #3: Cannot report on the current status of the physical element
6) UNKNOWN[Storage] Status of Intel Corporation C610/X99 series chipset PCI Express Root Port #1 #28: Cannot report on the current status of the physical element
7) UNKNOWN[Storage] Status of Intel Corporation C610/X99 series chipset PCI Express Root Port #4 #28: Cannot report on the current status of the physical element
8) UNKNOWN[Storage] Status of Intel Corporation C610/X99 series chipset PCI Express Root Port #5 #28: Cannot report on the current status of the physical element
9) UNKNOWN[Storage] Status of Intel Corporation C610/X99 series chipset LPC Controller #31: Cannot report on the current status of the physical element
10) UNKNOWN[Storage] Status of Renesas Technology Corp. SH7758 PCIe-PCI Bridge [PPB] #0: Cannot report on the current status of the physical element
11) UNKNOWN[Storage] Status of Intel Corporation Xeon E7 v4/Xeon E5 v4/Xeon E3 v4/Xeon D Map/VTd_Misc/System Management #5: Cannot report on the current status of the physical element
12) UNKNOWN[Storage] Status of Intel Corporation Xeon E7 v4/Xeon E5 v4/Xeon E3 v4/Xeon D IIO Hot Plug #5: Cannot report on the current status of the physical element
13) UNKNOWN[Storage] Status of Intel Corporation Xeon E7 v4/Xeon E5 v4/Xeon E3 v4/Xeon D IIO RAS/Control Status/Global Errors #5: Cannot report on the current status of the physical element
14) UNKNOWN[Storage] Status of Intel Corporation Xeon E7 v4/Xeon E5 v4/Xeon E3 v4/Xeon D I/O APIC #5: Cannot report on the current status of the physical element
15) UNKNOWN[Storage] Status of Intel Corporation C610/X99 series chipset SPSR #17: Cannot report on the current status of the physical element
16) UNKNOWN[Storage] Status of Intel Corporation Wellsburg AHCI Controller #17: Cannot report on the current status of the physical element
17) UNKNOWN[Storage] Status of Intel Corporation C610/X99 series chipset USB xHCI Host Controller #20: Cannot report on the current status of the physical element
18) UNKNOWN[Storage] Status of Intel Corporation C610/X99 series chipset MEI Controller #1 #22: Cannot report on the current status of the physical element
19) UNKNOWN[Storage] Status of Intel Corporation C610/X99 series chipset MEI Controller #2 #22: Cannot report on the current status of the physical element
20) UNKNOWN[Storage] Status of Intel Corporation C610/X99 series chipset USB Enhanced Host Controller #2 #26: Cannot report on the current status of the physical element
21) UNKNOWN[Storage] Status of Intel Corporation C610/X99 series chipset USB Enhanced Host Controller #1 #29: Cannot report on the current status of the physical element
22) UNKNOWN[Storage] Status of Intel Corporation Wellsburg AHCI Controller #31: Cannot report on the current status of the physical element
23) UNKNOWN[Storage] Status of Intel Corporation C610/X99 series chipset SMBus Controller #31: Cannot report on the current status of the physical element
24) UNKNOWN[Storage] Status of Intel Corporation C610/X99 series chipset Thermal Subsystem #31: Cannot report on the current status of the physical element
25) UNKNOWN[Storage] Status of Avago (LSI) MegaRAID SAS Invader Controller #0: Cannot report on the current status of the physical element
26) UNKNOWN[Storage] Status of Intel Corporation Ethernet Server Adapter I350-T2 #0: Cannot report on the current status of the physical element
27) UNKNOWN[Storage] Status of Intel Corporation Ethernet Server Adapter I350-T2 #0: Cannot report on the current status of the physical element
28) UNKNOWN[Storage] Status of Matrox Electronics Systems Ltd. G200eR2 #0: Cannot report on the current status of the physical element
29) UNKNOWN[Storage] Status of Renesas Technology Corp. SH7758 PCIe End-Point [PBI] #0: Cannot report on the current status of the physical element
30) UNKNOWN[Storage] Status of Broadcom Corporation NetXtreme BCM5719 Gigabit Ethernet #0: Cannot report on the current status of the physical element
31) UNKNOWN[Storage] Status of Broadcom Corporation NetXtreme BCM5719 Gigabit Ethernet #0: Cannot report on the current status of the physical element
32) UNKNOWN[Storage] Status of Broadcom Corporation NetXtreme BCM5719 Gigabit Ethernet #0: Cannot report on the current status of the physical element
33) UNKNOWN[Storage] Status of Broadcom Corporation NetXtreme BCM5719 Gigabit Ethernet #0: Cannot report on the current status of the physical element
34) UNKNOWN[Storage] Status of Intel Corporation Xeon E7 v4/Xeon E5 v4/Xeon E3 v4/Xeon D Map/VTd_Misc/System Management #5: Cannot report on the current status of the physical element
35) UNKNOWN[Storage] Status of Intel Corporation Xeon E7 v4/Xeon E5 v4/Xeon E3 v4/Xeon D IIO Hot Plug #5: Cannot report on the current status of the physical element
36) UNKNOWN[Storage] Status of Intel Corporation Xeon E7 v4/Xeon E5 v4/Xeon E3 v4/Xeon D IIO RAS/Control Status/Global Errors #5: Cannot report on the current status of the physical element
37) UNKNOWN[Storage] Status of Intel Corporation Xeon E7 v4/Xeon E5 v4/Xeon E3 v4/Xeon D I/O APIC #5: Cannot report on the current status of the physical element
38) UNKNOWN[Storage] Status of Renesas Technology Corp. SH7758 PCIe Switch [PS] #0: Cannot report on the current status of the physical element
39) UNKNOWN[Storage] Status of Socket 1 Level-2 Cache: Cannot report on the current status of the physical element
40) UNKNOWN[Storage] Status of Socket 1 Level-3 Cache: Cannot report on the current status of the physical element
41) UNKNOWN[Storage] Status of Socket 2 Level-1 Cache: Cannot report on the current status of the physical element
42) UNKNOWN[Storage] Status of Socket 2 Level-2 Cache: Cannot report on the current status of the physical element
43) UNKNOWN[Storage] Status of Socket 2 Level-3 Cache: Cannot report on the current status of the physical element | Alerts=43;;
`

With the command:
`
/usr/lib/nagios/plugins/check_vmware_api.pl -H 192.168.xx.xx -u user -p password -l runtime -s health`

Do you have a solution ?

Thank you

**Comment by hostmolch** [comment]
We face the same issue with SDK 6.5 and the latest ESX environment.

**Comment by Fly-Boy69** [comment]
Same problem....
1) UNKNOWN[watchdog] Status of BIOS 1 OS Watchdog Time 65 --- 0.34.1.113: Cannot report on the current health state of the element
2) UNKNOWN[memory] Status of BIOS 1 MSR Info Log 65 --- 0.34.1.40: Cannot report on the current health state of the element
and so on.......

While there is an option to "black list" via "-x" in the command, this option is broken and has no effect. Further there is no documentation on the correct syntax for the blacklist... how should it be formatted?

**Comment by dorianborovina** [comment]
+1
Having the same problem on the Dell Customized image 6.7
Dell R740 & T640 fully patched.

**Comment by gao8621** [comment]
+1

**Comment by fliix-de** [comment]
+1

**Comment by wattebausch** [comment]
+1

**Comment by discard-this** [comment]
Just upgraded from 6.5 to 6.7, now seeing this same problem.

**Comment by DamienLGD** [comment]
+1 (DL360G9 & DL160G9 with ilo, hponfcg, etc.. vibs)

**Comment by arogarth** [comment]
Same here on vCenter 6.7U2

**Comment by mehdicopter** [comment]
Any news from this issue ?

**Comment by flankengott** [comment]
Same here!
Any news from this issue?

**Comment by jacobbaungard** [comment]
This plugin is "deprecated" from our side, and so most likely won't see any updates. Sorry about that.

The following project, which was forked from this one, might be of interest to you: https://github.com/BaldMansMojo/check_vmware_esx/
