### ISSUE TITLE
Read only account to authenticate into ESX?

### ISSUE THREAD

**Issue by Alfaj0r** [ITRS-Group/system-addons-plugins-op5-check_vmware_api#26]
I created a local account on an ESX host with read-only access, and the checks fail to authenticate.

Is the only way to run the checks to use the "root" account on each ESX host?

**Comment by jacobbaungard** [comment]
This plugin is "deprecated" from our side, and so most likely won't see any updates. We are therefore closing all open issues. Sorry about that.

The following project, which was forked from this one, might be of interest to you: https://github.com/BaldMansMojo/check_vmware_esx/
