### ISSUE TITLE
Remove script name from output

### ISSUE THREAD

**Issue by taker218** [ITRS-Group/system-addons-plugins-op5-check_vmware_api#28]
Not really an important issue, but is it possible to remove the script name from the output of the script?

At the moment I set the variable $PROGNAME to "ESXI" so the output isn't that long.

But I would like to completely remove the scriptname from the output, so that the first thing in the Status information in nagios is "OK|CRITICAL|WARNING" or whatever the status might be.

Any help would be appreciated

**Comment by jacobbaungard** [comment]
This plugin is "deprecated" from our side, and so most likely won't see any updates. We are therefore closing all open issues. Sorry about that.

The following project, which was forked from this one, might be of interest to you: https://github.com/BaldMansMojo/check_vmware_esx/
