### ISSUE TITLE
VMWare UNKNOWN results can't be black listed.

### ISSUE THREAD

**Issue by Fly-Boy69** [ITRS-Group/system-addons-plugins-op5-check_vmware_api#29]
results such as 
1) UNKNOWN[watchdog] Status of BIOS 1 OS Watchdog Time 65 --- 0.34.1.113: Cannot report on the current health state of the element
2) UNKNOWN[memory] Status of BIOS 1 MSR Info Log 65 --- 0.34.1.40: Cannot report on the current health state of the element

can not be black listed via -x

**Comment by jacobbaungard** [comment]
This plugin is "deprecated" from our side, and so most likely won't see any updates. We are therefore closing all open issues. Sorry about that.

The following project, which was forked from this one, might be of interest to you: https://github.com/BaldMansMojo/check_vmware_esx/
