### ISSUE TITLE
problem running check in nagios

### ISSUE THREAD

**Issue by hAEzErdEsZ** [ITRS-Group/system-addons-plugins-op5-check_vmware_api#30]
Centos 7, Nagios 4.3.4, Perl 5.10.1, VMware-vSphere-Perl-SDK-6.7

I can run the checks from the command line, with my nagios user, but when nagios run the checks, I get errors.

from cmd
 ./check_vmware_api -H [hostname] -u [username] -p [password] -l runtime -s con
CHECK_VMWARE_API OK - connection state=connected

from nagios
$USER1$/check_vmware_api -H $HOSTADDRESS$ -u [username] -p [password] -l runtime -s con
CHECK_VMWARE_API CRITICALHOST RUNTIME - unknown subcommand

**Comment by jacobbaungard** [comment]
This plugin is "deprecated" from our side, and so most likely won't see any updates. We are therefore closing all open issues. Sorry about that.

The following project, which was forked from this one, might be of interest to you: https://github.com/BaldMansMojo/check_vmware_esx/
