### ISSUE TITLE
Check Device Latency throwing Criticals on USB port

### ISSUE THREAD

**Issue by klaypigeon** [ITRS-Group/system-addons-plugins-op5-check_vmware_api#31]
./check_vmware_api2.pl -H 10.10.10.200 -u user -p pass -l io -s device -w 100 -c 150
CHECK_VMWARE_API2.PL CRITICAL - io device latency=166 ms | io_device=166ms;100;150

When we investigate we find this is vmhba32 which is associated with the USB/SD port. Is there a way to exclude this? It doesn't really seem relevant here. I did try --exclude vmhba32 but that did nothing.

**Comment by jacobbaungard** [comment]
This plugin is "deprecated" from our side, and so most likely won't see any updates. We are therefore closing all open issues. Sorry about that.

The following project, which was forked from this one, might be of interest to you: https://github.com/BaldMansMojo/check_vmware_esx/
