### ISSUE TITLE
Hardware checks

### ISSUE THREAD

**Issue by omahonyb** [ITRS-Group/system-addons-plugins-op5-check_vmware_api#32]
Is it possible to check the HW via this check? We recently got alerts on a cisco host that has a pair of FlexFlash SD cards for ESX in a RAID1. However we never got any alerts via this api check.
I found a HW check, but unfortunately the hosts are on a segregated network from the monitoring server, so was unable to proceed with that one.

**Comment by jacobbaungard** [comment]
This plugin is "deprecated" from our side, and so most likely won't see any updates. We are therefore closing all open issues. Sorry about that.

The following project, which was forked from this one, might be of interest to you: https://github.com/BaldMansMojo/check_vmware_esx/
