### ISSUE TITLE
Check_vmware_api fails to run

### ISSUE THREAD

**Issue by trgrassijr55** [ITRS-Group/system-addons-plugins-op5-check_vmware_api#34]
Ubuntu 16.04.1 LTS
Nagios Core 4.3.4

trying to run 

root@tgcs017:/usr/local/nagios/libexec# ./check_vmware_api.pl -H Myhost-8
Can't locate Monitoring/Plugin/Functions.pm in @INC (you may need to install the Monitoring::Plugin::Functions module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ./check_vmware_api.pl line 39.

The instructions to set this plugin up are for cent os 

the yum install command fails 

I used apt-get install 

root@tgcs017:/usr/local/nagios/libexec# sudo apt-get install openssl-devel perl-ibXML perl-MIME-Lite perl-MIME-Types perl-MailTools perl-TimeDate uuid libuuid pect perl-Test-Simple perl-Monitoring-Plugin perl-Class-Accessor perl-Config-Tiny
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package openssl-devel
E: Unable to locate package perl-Archive-Zip
E: Unable to locate package perl-Class-MethodMaker
E: Unable to locate package uuid-perl
E: Unable to locate package perl-SOAP-Lite
E: Unable to locate package perl-XML-SAX
E: Unable to locate package perl-XML-NamespaceSupport
E: Unable to locate package perl-XML-LibXML
E: Unable to locate package perl-MIME-Lite
E: Unable to locate package perl-MIME-Types
E: Unable to locate package perl-MailTools
E: Unable to locate package perl-TimeDate
E: Unable to locate package libuuid
E: Unable to locate package perl-Data-Dump
E: Unable to locate package perl-uuid
E: Unable to locate package libuuid
E: Unable to locate package perl-Data-Dump
E: Unable to locate package perl-UUID
E: Unable to locate package cpan
E: Unable to locate package libxml2-devel
E: Unable to locate package perl-libwww-perl
E: Unable to locate package perl-Test-MockObject
E: Unable to locate package perl-Test-Simple
E: Unable to locate package perl-Monitoring-Plugin
E: Unable to locate package perl-Class-Accessor
E: Unable to locate package perl-Config-Tiny
root@tgcs017:/usr/local/nagios/libexec#

Tried yum also
root@tgcs017:/usr/local/nagios/libexec# sudo yum install openssl-devel perl-Archive-Zip perl-Class-MethodMaker uuid-perl perl-SOAP-Lite perl-XML-SAX perl-XML-NamespaceSupport  perl-XML-LibXML perl-MIME-Lite perl-MIME-Types perl-MailTools perl-TimeDate uuid libuuid perl-Data-Dump perl-uuid libuuid perl-Data-Dump perl-UUID cpan libxml2-devel perl-libwww-perl perl-Test-MockObject perl-Test-Simple perl-Monitoring-Plugin perl-Class-Accessor perl-Config-Tiny
There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 You can enable repos with yum-config-manager --enable <repo>
root@tgcs017:/usr/local/nagios/libexec# yum repolist all
repolist: 0
root@tgcs017:/usr/local/nagios/libexec#

**Comment by jacobbaungard** [comment]
This plugin is "deprecated" from our side, and so most likely won't see any updates. We are therefore closing all open issues. Sorry about that.

The following project, which was forked from this one, might be of interest to you: https://github.com/BaldMansMojo/check_vmware_esx/
