### ISSUE TITLE
Error host does not exist

### ISSUE THREAD

**Issue by CIVODUL4** [ITRS-Group/system-addons-plugins-op5-check_vmware_api#39]
Hi,

I try to update my old Nagios server by setting up a new one. I've installed all prerequisites and i face a strange problem. It seems i'm authenticated but the api returns me an error :

[root@nagios plugins]# ./check_vmware_api.pl -H 192.168.1.10 -u nagios -p password-l runtime -s status
Use of uninitialized value in concatenation (.) or string at ./check_vmware_api.pl line 1895.
CHECK_VMWARE_API.PL CRITICAL - Host "" does not exist

If I change the password, i got an authentication error meaning the user password and ip are correct ....

Any help on this will be appreciated.

**Comment by CIVODUL4** [comment]
Problème en cours de résolution, j'ai un problème de transmission des droits depuis mon Vcenter aux autres Datastores gérés.

**Comment by erikdsjostrom** [comment]
Sounds like you resolved the issue on your own. Closing.
