### ISSUE TITLE
check_vmware_v2

### ISSUE THREAD

**Issue by hmakmur** [ITRS-Group/system-addons-plugins-op5-check_vmware_api#42]
Any chance  you would share check_vmware_v2 to the public as described in https://support.itrsgroup.com/hc/en-us/articles/360020251833?flash_digest=b2c70d17e6c080829307a63e19f40939e5cb4e3e ?

**Comment by jacobbaungard** [comment]
HI @hmakmur, at this time there is no plans to open source that particular plugin.
