### ISSUE TITLE
Show host in maintenance mode in a cluster

### ISSUE THREAD

**Issue by d-zalewski** [ITRS-Group/system-addons-plugins-op5-check_vmware_api#8]
Hi,

Is it possible to query all hosts in maintenance mode in a specific cluster?

I have 100s of esx hosts in a cluster and would rather not to add a service check for each of them.

Thanks

Dom

**Comment by rhagman** [comment]
Hello,

Unfortunately this is not possible at the moment, but it sounds like a good use case so it would be a nice addition to the plugin. I will not have any time to add this functionality within the near future thou, but pull requests accompanied with tests are always welcomed.

Have a nice day!
